strr = "wwwwwwwwww"
strr = '''wwwwwwlsdjbjhvhagjshvahsdskhvasjhsanb<Bxvnbm,cjsvhsdjgvsabkjshgsdhjsvc,msabcnmsvcmb,zxvnmbxvcnmvxhjcgvsmnbavmanscbmnXVcnbmx 
cmnxvXcmnbxvcnmxvmnbzvxcmbxnbcvnzxvmnbcxzvmnbvnxzcvhkvcnmvxnmvznmxvmnxvbnxzvcmnbvnbvnmvcnvxzcnmvxcmnXZVmnxvcmnbvwwww'''