print("a" "\tb" "\tpow(a,b)")
print(str(1) +"\t" +str(2)+"\t" +str(1**2))
print(str(2) +"\t" +str(3)+"\t" +str(2**3))
print(str(3) +"\t" +str(4)+"\t" +str(3**4))
print(str(4) +"\t" +str(5)+"\t" +str(4**5))
print(str(5) +"\t" +str(6)+"\t" +str(5**6))